### ISSUE TITLE
[SKiDL BUG] AttributeError: 'list' object has no attribute 'search'

### ISSUE THREAD

**Issue by cyberhuman** [devbisme/skidl#258]
In the development branch, running the following program results in an error:
```python
from skidl import Part, TEMPLATE

LED0201 = Part("Device", "LED", dest=TEMPLATE, footprint="LED_SMD:LED_0201_0603Metric")
```

```
Traceback (most recent call last):
  File "/home/me/test/test.py", line 5, in <module>
    LED0201 = Part("Device", "LED", dest=TEMPLATE, footprint="LED_SMD:LED_0201_0603Metric")
  File "/home/me/skidl/src/skidl/part.py", line 261, in __init__
    part = lib[name].copy(dest=TEMPLATE)
           ~~~^^^^^^
  File "/home/me/skidl/src/skidl/schlib.py", line 208, in __getitem__
    return list_or_scalar(self.get_parts_by_name(id))
                          ~~~~~~~~~~~~~~~~~~~~~~^^^^
  File "/home/me/skidl/src/skidl/schlib.py", line 351, in get_parts_by_name
    part.parse(partial_parse)
    ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/me/skidl/src/skidl/part.py", line 723, in parse
    tool_modules[self.tool].parse_lib_part(self, partial_parse)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/skidl/src/skidl/tools/kicad8/lib.py", line 210, in parse_lib_part
    extends = part_defn.search("/symbol/extends", ignore_case=True)
              ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'search'
```

`git bisect` says
```
394610f72b8ccebc99a15e7ffdf91da01439f275 is the first bad commit
commit 394610f72b8ccebc99a15e7ffdf91da01439f275
Author: devbisme <devb@xess.com>
Date:   Fri May 30 20:53:02 2025 -0400

    - Replaced use of S-expression functions in utilities.py with Sexp class from simp_sexp package.

 src/skidl/tools/kicad5/gen_netlist.py |  43 ++++----
 src/skidl/tools/kicad6/gen_netlist.py |  43 ++++----
 src/skidl/tools/kicad6/lib.py         | 186 +++++++++++++++-------------------
 src/skidl/tools/kicad7/gen_netlist.py |  43 ++++----
 src/skidl/tools/kicad7/lib.py         | 186 +++++++++++++++-------------------
 src/skidl/tools/kicad8/gen_netlist.py |   2 +-
 src/skidl/tools/kicad8/lib.py         | 120 +++++++++++-----------
 src/skidl/tools/kicad9/gen_netlist.py |  43 ++++----
 src/skidl/tools/kicad9/lib.py         | 186 +++++++++++++++-------------------
 src/skidl/utilities.py                | 309 --------------------------------------------------------
 tests/unit_tests/test_lib.py          |   9 +-
 11 files changed, 406 insertions(+), 764 deletions(-)
```

**Comment by cyberhuman** [comment]
Indeed, that helped! Sorry for the hassle.

**Comment by cyberhuman** [comment]
It was removing the `lib_pickle_dir` that helped.
